use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ── Menu ──────────────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct DrinkRow {
    pub id:          i64,
    pub name:        String,
    pub description: String,
    pub price_cents: i32,
    pub category:    String,
    pub sort_order:  i32,
}

// ── Order creation ────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct OrderItem {
    pub drink_id: i64,
    pub quantity: i32,
}

#[derive(Debug, Deserialize)]
pub struct CreateVenueOrderBody {
    pub business_id:     i32,
    /// UUID generated by the client. Used to deduplicate retried requests.
    pub idempotency_key: String,
    pub items:           Vec<OrderItem>,
    pub notes:           Option<String>,
}

// ── Order response ────────────────────────────────────────────────────────────

#[derive(Debug, Serialize)]
pub struct VenueOrderResponse {
    pub order_id:      i64,
    /// Pass to Stripe's PaymentSheet on the client.
    pub client_secret: String,
    pub total_cents:   i32,
}

// ── Internal row ──────────────────────────────────────────────────────────────

#[derive(Debug, sqlx::FromRow)]
pub struct VenueOrderRow {
    pub id:                       i64,
    pub user_id:                  i32,
    pub business_id:              i32,
    pub stripe_payment_intent_id: Option<String>,
    pub square_order_id:          Option<String>,
    pub status:                   String,
    pub total_cents:              i32,
    pub platform_fee_cents:       i32,
    pub notes:                    String,
    pub created_at:               DateTime<Utc>,
}

// ── Stripe Connect onboarding ─────────────────────────────────────────────────

#[derive(Debug, Serialize)]
pub struct ConnectOnboardingResponse {
    pub onboarding_url: String,
}
